### Let us create an Artificial Neural Network for our Big Mart sales dataset and see how it will compare against the model we create in feature engineering and model building stage

#### 1.Importing necessary libraries

In [638]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
% matplotlib inline
import tensorflow as tf

- let us import the preprocessed file which we had earlier created.

In [639]:
file = "/content/drive/MyDrive/Colab Notebooks/projects/Big mart sales/Big_mart_processed.csv"
data = pd.read_csv(file)

In [640]:
data.head()

,item_identifier,item_weight,item_visibility,item_type,item_mrp,outlet_identifier,outlet_establishment_year,outlet_age_category,item_fat_content_0,item_fat_content_1,...,outlet_4,outlet_5,outlet_6,outlet_7,outlet_8,outlet_9,outlet_age_0,outlet_age_1,outlet_age_2,item_outlet_sales
0,FDA15,9.30,0.126678,Dairy,249.8092,OUT049,1999,Moderate outlet,1,0,...,0,0,0,0,0,1,1,0,0,61.115775
1,DRC01,5.92,0.138846,Soft Drinks,48.2692,OUT018,2009,New outlet,0,0,...,0,0,0,0,0,0,0,1,0,21.057607
2,FDN15,17.50,0.129461,Meat,141.6180,OUT049,1999,Moderate outlet,1,0,...,0,0,0,0,0,1,1,0,0,45.795961
3,FDX07,19.20,0.257161,Fruits and Vegetables,182.0950,OUT010,1998,Moderate outlet,0,0,...,0,0,0,0,0,0,1,0,0,27.062520
4,NCD19,8.93,0.257161,Household,53.8614,OUT013,1987,old outlet,0,1,...,0,0,0,0,0,0,0,0,1,31.538947

- let us drop all the features which will not be useful for the analysis

In [641]:
df = data.copy()

In [642]:
df.drop(['item_identifier','item_type','outlet_identifier','outlet_establishment_year','outlet_age_category'],axis=1,inplace=True)

In [643]:
df.head()

,item_weight,item_visibility,item_mrp,item_fat_content_0,item_fat_content_1,item_fat_content_2,outlet_size_0,outlet_size_1,outlet_size_2,outlet_location_type_0,...,outlet_4,outlet_5,outlet_6,outlet_7,outlet_8,outlet_9,outlet_age_0,outlet_age_1,outlet_age_2,item_outlet_sales
0,9.30,0.126678,249.8092,1,0,0,0,1,0,1,...,0,0,0,0,0,1,1,0,0,61.115775
1,5.92,0.138846,48.2692,0,0,1,0,1,0,0,...,0,0,0,0,0,0,0,1,0,21.057607
2,17.50,0.129461,141.6180,1,0,0,0,1,0,1,...,0,0,0,0,0,1,1,0,0,45.795961
3,19.20,0.257161,182.0950,0,0,1,0,1,0,0,...,0,0,0,0,0,0,1,0,0,27.062520
4,8.93,0.257161,53.8614,0,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,31.538947

#### 2.Train-Test-Split

In [644]:
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [645]:
print(X.shape,y.shape)

(8523, 32) (8523,)

In [646]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state =0)

    After Scaling the MSE increases so opted to not do scaling for this dataset

#### 3. Building the ANN

-  Initialising the ANN

In [647]:
ann = tf.keras.models.Sequential()

- Adding the input layer and the firs hidden layer

In [648]:
ann.add(tf.keras.layers.Dense(units=15, activation='relu'))

- Adding the second hidden layer

In [649]:
ann.add(tf.keras.layers.Dense(units=15, activation='relu'))

- Adding the third hidden layer

In [650]:
# ann.add(tf.keras.layers.Dense(units=7, activation='relu'))

- Adding the output layer

In [651]:
ann.add(tf.keras.layers.Dense(units=1))

### 4.Training the ANN

In [652]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

In [ ]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

In [654]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[47.08 37.76]
 [40.05 34.67]
 [45.27 42.85]
 ...
 [49.47 56.03]
 [27.53 32.6 ]
 [45.66 64.58]]

In [655]:
from sklearn.metrics import r2_score,mean_squared_error,accuracy_score

In [656]:
r2_score(y_test,y_pred)

0.6702918214671858

In [657]:
MSE = mean_squared_error(y_test,y_pred)
print('we have an MSE of:',MSE)

we have an MSE of: 114.45255503285229

In [658]:
import math
RMSE = math.sqrt(MSE)
print('we have an RMSE of',RMSE)

we have an RMSE of 10.698250092087598

Inferences:
- After a thourough experimentation here are the results:
  - For this dataset the optimal units we found is 9
  - an input layer -2 hidden layers and 1 output layer
  - batch size -32
  - epochs - 100-130 seems to yield good results
- There seems to be a slight change in the result compared to the previous 66 in the XgBoost regressor.
- This is just a simple neural network without any additional extra parameters as such, we can try to further increse our model performance by applying various parameters